<?php
declare(strict_types=1);
require_once __DIR__ . '/_bootstrap.php';

trux_require_login();
$me = trux_current_user();
if (!$me) {
    trux_redirect('/login.php');
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = $_POST['action'] ?? 'save_notifications';
    if ($action === 'unmute_user') {
        $rawMutedUserId = $_POST['muted_user_id'] ?? null;
        if (is_string($rawMutedUserId) && preg_match('/^\d+$/', $rawMutedUserId)) {
            trux_unmute_user((int)$me['id'], (int)$rawMutedUserId);
            trux_flash_set('success', 'User unmuted.');
        } else {
            trux_flash_set('error', 'Invalid muted user.');
        }
    } else {
        $submitted = [];
        foreach (array_keys(trux_notification_defaults()) as $key) {
            $submitted[$key] = isset($_POST[$key]) && $_POST[$key] === '1';
        }

        if (trux_update_notification_preferences((int)$me['id'], $submitted)) {
            trux_flash_set('success', 'Notification preferences updated.');
        } else {
            trux_flash_set('error', 'Could not update notification preferences right now.');
        }
    }

    trux_redirect('/settings.php');
}

$prefs = trux_fetch_notification_preferences((int)$me['id']);
$prefLabels = trux_notification_pref_labels();
$mutedUsers = trux_fetch_muted_users((int)$me['id']);

require_once __DIR__ . '/_header.php';
?>

<section class="hero">
  <h1>Settings</h1>
  <p class="muted">Manage the notifications you want to receive.</p>
</section>

<section class="card settingsCard">
  <div class="card__body">
    <form class="form settingsForm" method="post" action="<?= TRUX_BASE_URL ?>/settings.php">
      <?= trux_csrf_field() ?>
      <input type="hidden" name="action" value="save_notifications">

      <div class="settingSection">
        <div class="settingSection__head">
          <h2 class="h2">Notifications</h2>
          <p class="muted">Choose which activity should appear in your notification feed.</p>
        </div>

        <?php foreach ($prefLabels as $key => $meta): ?>
          <label class="settingRow" for="<?= trux_e($key) ?>">
            <span class="settingRow__label">
              <strong><?= trux_e((string)$meta['title']) ?></strong>
              <small class="muted"><?= trux_e((string)$meta['description']) ?></small>
            </span>
            <input
              id="<?= trux_e($key) ?>"
              type="checkbox"
              name="<?= trux_e($key) ?>"
              value="1"
              <?= !empty($prefs[$key]) ? 'checked' : '' ?>>
          </label>
        <?php endforeach; ?>
      </div>

      <div class="settingSection">
        <div class="settingRow">
          <span class="settingRow__label">
            <strong>Visual settings</strong>
            <small class="muted">The interface now uses the fixed classic baseline across the site.</small>
          </span>
          <strong class="muted">Removed</strong>
        </div>
      </div>

      <div class="row">
        <button class="btn" type="submit">Save settings</button>
      </div>
    </form>

    <div class="settingSection settingsSectionStandalone">
      <div class="settingSection__head">
        <h2 class="h2">Muted Users</h2>
        <p class="muted">You will not receive notifications generated by users you mute.</p>
      </div>

      <?php if (!$mutedUsers): ?>
        <div class="settingRow">
          <span class="settingRow__label">
            <strong>No muted users</strong>
            <small class="muted">Mute a user from their profile to hide their likes, replies, follows, mentions, and vote notifications.</small>
          </span>
          <strong class="muted">0</strong>
        </div>
      <?php else: ?>
        <?php foreach ($mutedUsers as $mutedUser): ?>
          <div class="settingRow">
            <span class="settingRow__label">
              <strong>
                <a href="<?= TRUX_BASE_URL ?>/profile.php?u=<?= urlencode((string)$mutedUser['username']) ?>">@<?= trux_e((string)$mutedUser['username']) ?></a>
              </strong>
              <small class="muted">
                Muted
                <span
                  data-time-ago="1"
                  data-time-source="<?= trux_e((string)$mutedUser['created_at']) ?>"
                  title="<?= trux_e(trux_format_exact_time((string)$mutedUser['created_at'])) ?>">
                  <?= trux_e(trux_time_ago((string)$mutedUser['created_at'])) ?>
                </span>
              </small>
            </span>
            <form method="post" action="<?= TRUX_BASE_URL ?>/settings.php" class="inline">
              <?= trux_csrf_field() ?>
              <input type="hidden" name="action" value="unmute_user">
              <input type="hidden" name="muted_user_id" value="<?= (int)$mutedUser['id'] ?>">
              <button class="btn btn--small btn--ghost" type="submit">Unmute</button>
            </form>
          </div>
        <?php endforeach; ?>
      <?php endif; ?>
    </div>
  </div>
</section>

<?php require_once __DIR__ . '/_footer.php'; ?>
