ALTER TABLE posts
  ADD COLUMN IF NOT EXISTS edited_at DATETIME NULL DEFAULT NULL AFTER created_at;

ALTER TABLE post_comments
  ADD COLUMN IF NOT EXISTS edited_at DATETIME NULL DEFAULT NULL AFTER created_at;
