ALTER TABLE users
  ADD COLUMN IF NOT EXISTS display_name VARCHAR(80) NULL DEFAULT NULL AFTER email;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS bio VARCHAR(280) NULL DEFAULT NULL AFTER display_name;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS location VARCHAR(100) NULL DEFAULT NULL AFTER bio;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS website_url VARCHAR(255) NULL DEFAULT NULL AFTER location;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS avatar_path VARCHAR(255) NULL DEFAULT NULL AFTER website_url;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS banner_path VARCHAR(255) NULL DEFAULT NULL AFTER avatar_path;
